"""Generates the prescription samples: a PDF and a phone-photo JPEG per recorded fixture.

Each pair is rendered from `backend/tests/fixtures/ocr/sample_prescription*.json`. That pairing
matters: with `DEMO_MODE=true` and no Document Intelligence endpoint, an uploaded *image* cannot
be read locally, so `services/ocr.py` replays those fixtures. A photo showing anything else would
disagree with what the app reports on screen. (Uploaded PDFs are genuinely parsed, so their text
is what gets analyzed.)

Run: uv run --project backend python scripts/build_prescription_samples.py
"""

from __future__ import annotations

import json
import random
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

REPO_ROOT = Path(__file__).resolve().parents[1]
FIXTURE_DIR = REPO_ROOT / "backend" / "tests" / "fixtures" / "ocr"
DOCUMENTS_DIR = REPO_ROOT / "data" / "samples" / "documents"
PHOTOS_DIR = REPO_ROOT / "data" / "samples" / "photoes"

_FONT_DIR = Path("C:/Windows/Fonts")
_PAPER = (250, 247, 240)
_BANNER = (
    "SYNTHETIC DEMO DOCUMENT - NOT A REAL PRESCRIPTION. "
    "Generated by scripts/build_prescription_samples.py."
)

# fixture -> (clinic, registration, date, pdf stem, photo stem)
SAMPLES: tuple[tuple[str, str, str, str, str, str], ...] = (
    (
        "sample_prescription.json",
        "Demo Clinic",
        "DEMO-CLINIC-0001",
        "2026-09-01",
        "prescription-01-three-medicines",
        "prescription-photo-01",
    ),
    (
        "sample_prescription_02.json",
        "Sunrise Family Practice (demo)",
        "DEMO-CLINIC-0042",
        "2026-09-05",
        "prescription-02-gastro-and-bp",
        "prescription-photo-02",
    ),
)


def _font(candidates: list[str], size: int) -> ImageFont.FreeTypeFont:
    """First available TrueType face, falling back to Pillow's bitmap font."""
    for name in candidates:
        path = _FONT_DIR / name
        if path.exists():
            return ImageFont.truetype(str(path), size)
    return ImageFont.load_default(size)


def _read_fixture(name: str) -> tuple[str, str, list[dict]]:
    lines = json.loads((FIXTURE_DIR / name).read_text(encoding="utf-8"))["lines"]
    return lines[0]["text"], lines[1]["text"], lines[2:]


def build_pdf(fixture: str, clinic: str, registration: str, date: str, out_path: Path) -> None:
    prescriber, patient, medicines = _read_fixture(fixture)
    styles = getSampleStyleSheet()

    story = [
        Paragraph(f"<font color='#b45309'><b>{_BANNER}</b></font>", styles["BodyText"]),
        Spacer(1, 6 * mm),
        Paragraph(clinic, styles["Title"]),
        Paragraph(
            f"12 Example Road, Bengaluru 560001 &nbsp;|&nbsp; Reg. {registration}", styles["Normal"]
        ),
        Spacer(1, 5 * mm),
        Paragraph(f"<b>{prescriber}</b>", styles["Normal"]),
        Paragraph(patient, styles["Normal"]),
        Paragraph(f"Prescribed on {date}", styles["Normal"]),
        Spacer(1, 7 * mm),
        Paragraph("<b>Rx</b>", styles["Heading2"]),
    ]

    for index, line in enumerate(medicines, start=1):
        story.append(Paragraph(f"{index}. {line['text']}", styles["BodyText"]))
        story.append(Spacer(1, 2 * mm))

    story += [
        Spacer(1, 12 * mm),
        Paragraph("Signature: ____________________", styles["BodyText"]),
        Spacer(1, 6 * mm),
        Paragraph(
            "<font size=8 color='#64748b'>Synthetic data. Any resemblance to a real patient or "
            "prescriber is coincidental.</font>",
            styles["BodyText"],
        ),
    ]

    SimpleDocTemplate(
        str(out_path),
        pagesize=A4,
        title="Demo prescription (synthetic)",
        author="Health IQ (synthetic sample)",
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
    ).build(story)


def _photograph(canvas: Image.Image, *, tilt: float, seed: int) -> Image.Image:
    """Make a flat render look like a phone snap: uneven light, slight tilt, soft focus, noise."""
    width, height = canvas.size

    gradient = Image.new("L", (width, height))
    draw = ImageDraw.Draw(gradient)
    for y in range(height):
        draw.line([(0, y), (width, y)], fill=int(215 + 40 * (y / height)))
    canvas = Image.composite(canvas, Image.new("RGB", canvas.size, (238, 232, 222)), gradient)

    canvas = canvas.rotate(tilt, resample=Image.BICUBIC, expand=True, fillcolor=(90, 92, 96))
    canvas = canvas.filter(ImageFilter.GaussianBlur(0.4))

    rng = random.Random(seed)
    pixels = canvas.load()
    for _ in range((canvas.width * canvas.height) // 40):
        x = rng.randrange(canvas.width)
        y = rng.randrange(canvas.height)
        r, g, b = pixels[x, y]
        jitter = rng.randint(-12, 12)
        pixels[x, y] = (
            max(0, min(255, r + jitter)),
            max(0, min(255, g + jitter)),
            max(0, min(255, b + jitter)),
        )
    return canvas


def build_photo(
    fixture: str,
    clinic: str,
    registration: str,
    date: str,
    out_path: Path,
    *,
    tilt: float,
    seed: int,
) -> None:
    prescriber, patient, medicines = _read_fixture(fixture)

    canvas = Image.new("RGB", (1240, 1750), _PAPER)
    draw = ImageDraw.Draw(canvas)

    clinic_font = _font(["seguisb.ttf", "segoeuib.ttf", "arialbd.ttf"], 54)
    body = _font(["segoeui.ttf", "arial.ttf"], 40)
    small = _font(["segoeui.ttf", "arial.ttf"], 32)
    script = _font(["segoesc.ttf", "Inkfree.ttf", "comic.ttf", "arial.ttf"], 52)

    draw.text((90, 90), clinic, font=clinic_font, fill=(28, 60, 52))
    draw.text(
        (90, 165),
        f"12 Example Road, Bengaluru 560001 | Reg. {registration}",
        font=small,
        fill=(110, 112, 118),
    )
    draw.line([(90, 225), (1150, 225)], fill=(28, 60, 52), width=3)

    draw.text((90, 265), prescriber, font=body, fill=(40, 42, 48))
    draw.text((90, 325), patient, font=body, fill=(40, 42, 48))
    draw.text((90, 385), f"Date: {date}", font=body, fill=(40, 42, 48))
    draw.text((90, 480), "Rx", font=_font(["timesbd.ttf", "arialbd.ttf"], 76), fill=(30, 58, 96))

    y = 600
    for index, line in enumerate(medicines, start=1):
        # The fixture's low-confidence line is the handwriting-heavy one; render it accordingly.
        faint = line["confidence"] < 0.75
        draw.text(
            (120, y),
            f"{index}.  {line['text']}",
            font=script if faint else body,
            fill=(70, 78, 130) if faint else (40, 42, 48),
        )
        y += 110

    draw.line([(90, 1400), (520, 1400)], fill=(60, 62, 68), width=2)
    draw.text((90, 1420), "Signature", font=small, fill=(120, 122, 128))
    draw.text(
        (90, 1600),
        "Synthetic demo document - not a real prescription.",
        font=small,
        fill=(150, 120, 60),
    )

    _photograph(canvas, tilt=tilt, seed=seed).save(out_path, "JPEG", quality=86)


def main() -> None:
    """Writes only what is missing, so committed samples are never silently rewritten.

    Delete a file and re-run to regenerate it.
    """
    DOCUMENTS_DIR.mkdir(parents=True, exist_ok=True)
    PHOTOS_DIR.mkdir(parents=True, exist_ok=True)

    for index, (fixture, clinic, registration, date, pdf_stem, photo_stem) in enumerate(SAMPLES):
        pdf_path = DOCUMENTS_DIR / f"{pdf_stem}.pdf"
        photo_path = PHOTOS_DIR / f"{photo_stem}.jpg"

        if pdf_path.exists():
            print(f"skip {pdf_path.name} (exists)")
        else:
            build_pdf(fixture, clinic, registration, date, pdf_path)
            print(f"wrote {pdf_path.name}")

        if photo_path.exists():
            print(f"skip {photo_path.name} (exists)")
        else:
            build_photo(
                fixture,
                clinic,
                registration,
                date,
                photo_path,
                tilt=-1.4 if index % 2 == 0 else 1.1,
                seed=20260909 + index,
            )
            print(f"wrote {photo_path.name}")


if __name__ == "__main__":
    main()
