"""Generates the lab-report samples: a PDF and a phone-photo JPEG per recorded fixture.

Each pair is rendered from `backend/tests/fixtures/ocr/sample_lab_report_*.json`. That pairing
matters for the photos: without a Document Intelligence endpoint or a local Tesseract install,
`services/ocr.py` cannot read an uploaded image and replays those fixtures instead, in the same
order. A photo showing other values would disagree with what the app reports on screen.

Uploaded PDFs are genuinely parsed, so their printed table is what gets analyzed.

Run: uv run --project backend python scripts/build_lab_report_samples.py
"""

from __future__ import annotations

import json
import random
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

REPO_ROOT = Path(__file__).resolve().parents[1]
FIXTURE_DIR = REPO_ROOT / "backend" / "tests" / "fixtures" / "ocr"
DOCUMENTS_DIR = REPO_ROOT / "data" / "samples" / "documents"
PHOTOS_DIR = REPO_ROOT / "data" / "samples" / "photoes"

_FONT_DIR = Path("C:/Windows/Fonts")
_PAPER = (252, 251, 247)
_BANNER = (
    "SYNTHETIC DEMO DOCUMENT - NOT A REAL LAB REPORT. "
    "Generated by scripts/build_lab_report_samples.py."
)

# fixture -> (pdf stem, photo stem, tilt, seed). Order matches the OCR fixture rotation.
SAMPLES: tuple[tuple[str, str, str, float, int], ...] = (
    (
        "sample_lab_report_older.json",
        "lab-report-01-older-2026-03-10",
        "lab-report-photo-01-older",
        -1.1,
        20260310,
    ),
    (
        "sample_lab_report_newer.json",
        "lab-report-02-newer-2026-06-14",
        "lab-report-photo-02-newer",
        1.3,
        20260614,
    ),
)


def _font(candidates: list[str], size: int) -> ImageFont.FreeTypeFont:
    """First available TrueType face, falling back to Pillow's bitmap font."""
    for name in candidates:
        path = _FONT_DIR / name
        if path.exists():
            return ImageFont.truetype(str(path), size)
    return ImageFont.load_default(size)


def _read_fixture(name: str) -> tuple[list[str], list[list[str]]]:
    raw = json.loads((FIXTURE_DIR / name).read_text(encoding="utf-8"))
    return [line["text"] for line in raw["lines"]], raw["tables"][0]


def build_pdf(fixture: str, out_path: Path) -> None:
    headers, table_rows = _read_fixture(fixture)
    styles = getSampleStyleSheet()

    table = Table(table_rows, repeatRows=1, hAlign="LEFT")
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f766e")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#c9d3df")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f4f7fb")]),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )

    story = [
        Paragraph(f"<font color='#b45309'><b>{_BANNER}</b></font>", styles["BodyText"]),
        Spacer(1, 6 * mm),
        Paragraph(headers[0], styles["Title"]),
        Paragraph("NABL-equivalent demo laboratory &nbsp;|&nbsp; Reg. DEMO-LAB-0001", styles["Normal"]),
        Spacer(1, 5 * mm),
        Paragraph("Patient: Rohan Sharma &nbsp;&nbsp; Age/Sex: 42 / M", styles["Normal"]),
        Paragraph(headers[1], styles["Normal"]),
        Spacer(1, 6 * mm),
        Paragraph(headers[2], styles["Heading2"]),
        Spacer(1, 2 * mm),
        table,
        Spacer(1, 8 * mm),
        Paragraph(
            "<font size=8 color='#64748b'>Reference ranges shown are demo values. "
            "Synthetic data - not a real laboratory result.</font>",
            styles["BodyText"],
        ),
    ]

    SimpleDocTemplate(
        str(out_path),
        pagesize=A4,
        title="Demo lab report (synthetic)",
        author="Health IQ (synthetic sample)",
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
    ).build(story)


def _photograph(canvas: Image.Image, *, tilt: float, seed: int) -> Image.Image:
    """Make a flat render look like a phone snap: uneven light, slight tilt, soft focus, noise."""
    width, height = canvas.size

    gradient = Image.new("L", (width, height))
    draw = ImageDraw.Draw(gradient)
    for y in range(height):
        draw.line([(0, y), (width, y)], fill=int(212 + 42 * (y / height)))
    canvas = Image.composite(canvas, Image.new("RGB", canvas.size, (236, 231, 221)), gradient)

    canvas = canvas.rotate(tilt, resample=Image.BICUBIC, expand=True, fillcolor=(88, 90, 95))
    canvas = canvas.filter(ImageFilter.GaussianBlur(0.4))

    rng = random.Random(seed)
    pixels = canvas.load()
    for _ in range((canvas.width * canvas.height) // 40):
        x = rng.randrange(canvas.width)
        y = rng.randrange(canvas.height)
        r, g, b = pixels[x, y]
        jitter = rng.randint(-11, 11)
        pixels[x, y] = (
            max(0, min(255, r + jitter)),
            max(0, min(255, g + jitter)),
            max(0, min(255, b + jitter)),
        )
    return canvas


def build_photo(fixture: str, out_path: Path, *, tilt: float, seed: int) -> None:
    headers, table_rows = _read_fixture(fixture)
    header_row, *data_rows = table_rows

    canvas = Image.new("RGB", (1240, 1754), _PAPER)
    draw = ImageDraw.Draw(canvas)

    lab_font = _font(["seguisb.ttf", "segoeuib.ttf", "arialbd.ttf"], 52)
    body = _font(["segoeui.ttf", "arial.ttf"], 34)
    cell = _font(["segoeui.ttf", "arial.ttf"], 30)
    cell_bold = _font(["seguisb.ttf", "arialbd.ttf"], 30)
    small = _font(["segoeui.ttf", "arial.ttf"], 26)

    draw.text((80, 80), headers[0], font=lab_font, fill=(18, 70, 62))
    draw.text((80, 148), "NABL-equivalent demo laboratory  |  Reg. DEMO-LAB-0001", font=small, fill=(112, 116, 124))
    draw.line([(80, 200), (1160, 200)], fill=(18, 70, 62), width=3)

    draw.text((80, 232), "Patient: Rohan Sharma    Age/Sex: 42 / M", font=body, fill=(40, 42, 48))
    draw.text((80, 284), headers[1], font=body, fill=(40, 42, 48))
    draw.text((80, 350), headers[2], font=_font(["seguisb.ttf", "arialbd.ttf"], 40), fill=(20, 40, 70))

    columns = [80, 520, 700, 880]
    y = 420
    draw.rectangle([70, y - 12, 1170, y + 46], fill=(15, 118, 110))
    for index, label in enumerate(header_row):
        draw.text((columns[index], y), label, font=cell_bold, fill=(255, 255, 255))
    y += 62

    for row_index, row in enumerate(data_rows):
        if row_index % 2 == 1:
            draw.rectangle([70, y - 10, 1170, y + 44], fill=(244, 247, 251))
        for index, value in enumerate(row):
            draw.text((columns[index], y), value, font=cell, fill=(38, 40, 46))
        y += 58

    draw.line([(70, y + 6), (1170, y + 6)], fill=(200, 206, 214), width=2)
    draw.text(
        (80, y + 40),
        "Reference ranges shown are demo values.",
        font=small,
        fill=(112, 116, 124),
    )
    draw.text(
        (80, y + 84),
        "Synthetic demo document - not a real laboratory result.",
        font=small,
        fill=(150, 120, 60),
    )

    _photograph(canvas, tilt=tilt, seed=seed).save(out_path, "JPEG", quality=87)


def main() -> None:
    """Writes only what is missing, so committed samples are never silently rewritten."""
    DOCUMENTS_DIR.mkdir(parents=True, exist_ok=True)
    PHOTOS_DIR.mkdir(parents=True, exist_ok=True)

    for fixture, pdf_stem, photo_stem, tilt, seed in SAMPLES:
        pdf_path = DOCUMENTS_DIR / f"{pdf_stem}.pdf"
        photo_path = PHOTOS_DIR / f"{photo_stem}.jpg"

        if pdf_path.exists():
            print(f"skip {pdf_path.name} (exists)")
        else:
            build_pdf(fixture, pdf_path)
            print(f"wrote {pdf_path.name}")

        if photo_path.exists():
            print(f"skip {photo_path.name} (exists)")
        else:
            build_photo(fixture, photo_path, tilt=tilt, seed=seed)
            print(f"wrote {photo_path.name}")


if __name__ == "__main__":
    main()
